name: CI to docker hub

on:
  push:
    branches: [ master ]

jobs:
  Build_and_Push_latest:
    uses: ./.github/workflows/docker_build_push.yml
    with:
      docker_tag: latest
    secrets: inherit
