name: Tag to docker hub

on:
  push:
    tags: [ v* ]

jobs:
  Build_and_Push_tag:
    uses: ./.github/workflows/docker_build_push.yml
    with:
      docker_tag: ${{github.ref_name}}
    secrets: inherit
